### PR TITLE
Link to remark-behead (related)

### PR DESCRIPTION
**Pull request by millette**

### CODE REVIEW

**Comment by wooorm** [comment]
Ah, didn’t know the other repo was archived. Could you remove the line about `remark-rewrite-headers` and “steal” its description?

**Comment by wooorm** [comment]
@millette Friendly ping!

**Comment by millette** [comment]
@wooorm Oups, this had completely slipped my mind. Here you go, thanks for the ping.

**Comment by wooorm** [comment]
Thanks @millette!

**Pull request merged**
